### ISSUE TITLE
Upload a Video AND Get the Encoding Job ID?

### ISSUE THREAD

**Issue by Grandizer** [Telestream/telestream-cloud-.Net-sdk#2]
Hey there,

I came across this great tool while trying to deal with Telestream in .Net.  Works great when downloading/viewing and such.

I am now at the point of uploading.  I can upload a video and it goes great with your UploadFile method.  However, it has not response object so I am not sure how to get the unique ID that Telestream assigns it when uploaded.  Am I using the wrong method to upload a file?  Can I preload a unique ID for Telestream?

Thank you

**Comment by ucatunit** [comment]
Hi Kevin - just letting you know that fix for the issue you’ve reported is pushed to the master.
